[theme]
primaryColor="#1E88E5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[server]
maxUploadSize=200
enableXsrfProtection=true

[browser]
gatherUsageStats=false

[runner]
# Add system call enablement for playwright
magicEnabled = true
